title: ethanfahy.cloud
description: Ethan Fahy's Software Engineering Blog
author: Ethan Fahy
email: ethanfahy@gmail.com
baseurl: ""
url: "https://ethanfahy.cloud"
github_username: ethanfahy
linkedin_username: ethanfahy
# JEKYLL_ENV=production must be set during jekyll build 
# for google_analytics to be enabled
google_analytics: UA-150564241-1

theme: minima
plugins:
  - jekyll-feed
