title: ethanfahy.cloud
description: Ethan Fahy's Software Engineering Blog
author: Ethan Fahy
email: ethanfahy@gmail.com
baseurl: ""
url: "https://ethanfahy.cloud"
github_username: ethanfahy
twitter_username: EthanHFahy
linkedin_username: ethanfahy

theme: minima
plugins:
  - jekyll-feed
